name: Sync NeoDB Data

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  neodb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.0

      - name: Install dependencies
        run: pnpm install

      - name: Sync WakaTime and Hitokoto
        env:
          GH_SECERT: ${{ secrets.GH_SECERT }}
          WAKABOX_GIST_ID: ${{ secrets.WAKABOX_GIST_ID }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          HITOKOTO_GIST_ID: ${{ secrets.HITOKOTO_GIST_ID }}
          CATEGORY: ${{ secrets.CATEGORY }}
        run: |
          pnpm run wakabox
          pnpm run hitokoto
